### ISSUE TITLE
Does not compile with serde 0.10

### ISSUE THREAD

**Issue by Narfinger** [dermesser/yup-oauth2#55]
Currently, if you try to compile with serde 0.10 compilation fails with the following error:

`
error[E0277]: the trait bound `oauth2::ApplicationSecret: serde::Deserialize` is not satisfied
  --> src/main.rs:90:18
   |
90 |     let secret = json::from_reader::<File,ApplicationSecret>(f).unwrap().unwrap();
   |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `serde::Deserialize` is not implemented for `oauth2::ApplicationSecret`
`

**Comment by ghost** [comment]
I think this should work when #54 lands.

**Comment by ghost** [comment]
@dermesser Once you are happy with my changes (merged already), please feel free to republish. I am preparing a serde v0.10 release of the google-apis in the meanwhile, but would depend on the changes made by the PR as well.

**Comment by dermesser** [comment]
Just published v1.0.4.

**Comment by Narfinger** [comment]
Ok this fixed it.
